apiVersion: v1 
kind: Pod 
metadata:
   name: emptydir
   namespace: ephermal
   labels:
      name: emptydir

spec:
   containers:
   - name: nginx
     image: nginx:latest
     volumeMounts:
     - mountPath: /var/log/nginx
       name: nginx-logs
   - name: almalinux
     image: almalinux:9
     command: ["sleep","1000"]
     volumeMounts:
     - mountPath: /mnt/logs
       name: nginx-logs
       readOnly: true    
   volumes:   
   - name: nginx-logs
     emptyDir:
        sizeLimit: 100Mi

