# this yml doing ---> creating persistent volume (creating disk) 
#and claimming tht disk and attaching it to pod tht external disk

apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # reclycle means delete data and dont delete disk and *Retain*: retain means don't delete data *delete* means delete the disk
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-024ebfb6400407c98
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-claim  # we need to give this name to pod at volumes.
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
     purpose: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: nginx-html # vloume name
      mountPath: /usr/share/nginx/html # the path in container
  nodeSelector:
      topology.kubernetes.io/zone: us-east-1a

  volumes:
  - name: nginx-html # we use this name at volumeMount
    persistentVolumeClaim:
      claimName: ebs-static-claim 

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-ebs-static

spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
      
