apiVersion: v1 
kind: Pod
metadata:
  namespace: roboshop
  name: frontend
  labels:
    purpose: containers
    environment: development
    project: roboshop

spec:
  containers:
  - name: frontend
    image: nginx    