apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport

spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    environment: dev
    purpose: nodeport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
