apiVersion: v1
kind: Service
metadata:
   name: nginx-nodeport

spec:
  selector:
    type: NodePort
    project: roboshop
    component: frontend
    environment: dev
    purpose: nodeport
  ports:
     - protocol: TCP
       port: 80 # sevice port
       targetPort: 80 # container port   forwart req to another container